
if( txtcolorprmHead === 'hover:text-inherit' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-current' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-transparent' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-black' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-white' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-slate-50' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-slate-100' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-slate-200' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-slate-300' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-slate-400' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-slate-500' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-slate-600' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-slate-700' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-slate-800' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-slate-900' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-gray-50' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-gray-100' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-gray-200' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-gray-300' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-gray-400' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-gray-500' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-gray-600' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-gray-700' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-gray-800' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-gray-900' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-zinc-50' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-zinc-100' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-zinc-200' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-zinc-300' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-zinc-400' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-zinc-500' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-zinc-600' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-zinc-700' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-zinc-800' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-zinc-900' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-neutral-50' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-neutral-100' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-neutral-200' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-neutral-300' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-neutral-400' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-neutral-500' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-neutral-600' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-neutral-700' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-neutral-800' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-neutral-900' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-stone-50' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-stone-100' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-stone-200' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-stone-300' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-stone-400' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-stone-500' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-stone-600' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-stone-700' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-stone-800' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-stone-900' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-red-50' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-red-100' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-red-200' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-red-300' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-red-400' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-red-500' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-red-600' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-red-700' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-red-800' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-red-900' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-orange-50' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-orange-100' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-orange-200' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-orange-300' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-orange-400' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-orange-500' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-orange-600' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-orange-700' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-orange-800' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-orange-900' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-amber-50' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-amber-100' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-amber-200' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-amber-300' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-amber-400' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-amber-500' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-amber-600' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-amber-700' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-amber-800' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-amber-900' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-yellow-50' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-yellow-100' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-yellow-200' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-yellow-300' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-yellow-400' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-yellow-500' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-yellow-600' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-yellow-700' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-yellow-800' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-yellow-900' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-lime-50' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-lime-100' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-lime-200' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-lime-300' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-lime-400' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-lime-500' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-lime-600' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-lime-700' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-lime-800' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-lime-900' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-green-50' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-green-100' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-green-200' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-green-300' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-green-400' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-green-500' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-green-600' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-green-700' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-green-800' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-green-900' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-emerald-50' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-emerald-100' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-emerald-200' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-emerald-300' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-emerald-400' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-emerald-500' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-emerald-600' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-emerald-700' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-emerald-800' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-emerald-900' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-teal-50' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-teal-100' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-teal-200' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-teal-300' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-teal-400' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-teal-500' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-teal-600' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-teal-700' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-teal-800' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-teal-900' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-cyan-50' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-cyan-100' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-cyan-200' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-cyan-300' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-cyan-400' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-cyan-500' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-cyan-600' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-cyan-700' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-cyan-800' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-cyan-900' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-sky-50' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-sky-100' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-sky-200' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-sky-300' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-sky-400' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-sky-500' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-sky-600' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-sky-700' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-sky-800' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-sky-900' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-blue-50' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-blue-100' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-blue-200' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-blue-300' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-blue-400' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-blue-500' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-blue-600' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-blue-700' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-blue-800' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-blue-900' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-indigo-50' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-indigo-100' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-indigo-200' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-indigo-300' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-indigo-400' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-indigo-500' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-indigo-600' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-indigo-700' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-indigo-800' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-indigo-900' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-violet-50' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-violet-100' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-violet-200' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-violet-300' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-violet-400' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-violet-500' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-violet-600' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-violet-700' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-violet-800' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-violet-900' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-purple-50' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-purple-100' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-purple-200' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-purple-300' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-purple-400' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-purple-500' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-purple-600' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-purple-700' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-purple-800' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-purple-900' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-fuchsia-50' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-fuchsia-100' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-fuchsia-200' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-fuchsia-300' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-fuchsia-400' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-fuchsia-500' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-fuchsia-600' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-fuchsia-700' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-fuchsia-800' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-fuchsia-900' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-pink-50' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-pink-100' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-pink-200' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-pink-300' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-pink-400' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-pink-500' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-pink-600' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-pink-700' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-pink-800' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-pink-900' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-rose-50' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-rose-100' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-rose-200' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-rose-300' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-rose-400' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-rose-500' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-rose-600' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-rose-700' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-rose-800' ? txtcolorprmHead : txtcolorprmHead) {}
if( txtcolorprmHead === 'hover:text-rose-900' ? txtcolorprmHead : txtcolorprmHead) {}
